version: '3'
services:
  mailcatcher:
    container_name: mailcatcher
    build: ./docker/mailcatcher
    restart: always
    ports:
       - "1080:1080"

  wpdb:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    links:
      - wpdb
      - mailcatcher
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wpdb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes: 
      - ./wp-content:/var/www/html/wp-content/
volumes:
   db_data:
